name: Daily Football Analysis

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Permet le déclenchement manuel depuis l'UI

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    env:
      FOOTBALL_KEY: ${{ secrets.FOOTBALL_KEY }}
      GRQ_KEY: ${{ secrets.GRQ_KEY }}
      GIT_REMOTE: origin
      GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME || 'github-actions[bot]' }}
      GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL || '41898282+github-actions[bot]@users.noreply.github.com' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # nécessaire pour push et historique complet
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Ensure script filename
        run: |
          if [ -f "ylanyyy.py" ]; then
            mv ylanyyy.py Analyse.py
            git add Analyse.py || true
          elif [ -f "yyred.py" ]; then
            mv yyred.py Analyse.py
            git add Analyse.py || true
          else
            echo "No source script (ylanyyy.py or yyred.py) found in repo root. Ensure Analyse.py exists."
          fi

      - name: Make Analyse.py executable
        run: |
          if [ -f "Analyse.py" ]; then
            chmod +x Analyse.py
          fi

      - name: Run analysis script
        id: run_analysis
        run: |
          if [ ! -f "Analyse.py" ]; then
            echo "Analyse.py not found, exiting."
            exit 1
          fi
          echo "Running analysis..."
          python --version
          pip --version
          python Analyse.py

      - name: Commit and push results (if any)
        if: ${{ always() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${GIT_AUTHOR_NAME}"
          git config user.email "${GIT_AUTHOR_EMAIL}"

          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "chore: add daily analysis results $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "Nothing to commit"
            git push "${GIT_REMOTE}" HEAD || echo "Push failed (probably no changes)."
          else
            echo "✅ No changes to commit."
          fi
