name: Run Daily Script

on:
  schedule:
    - cron: '0 6 * * *'  # chaque jour à 06h00 UTC
  workflow_dispatch:      # exécution manuelle possible

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python yy.py

      - name: Commit JSON results
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add *.json
          git commit -m "Daily data update $(date)" || echo "No changes to commit"
          git push
